### ISSUE TITLE
Handle the user iban as a set in the update function

### ISSUE THREAD

**Issue by leonardohscastilho** [in-fin-neat/in-fin-neat-core#55]
Currently the update function uses a regular list to deal with the user ibans. Handling it as a set will be more performant and cleaner. Context: https://github.com/in-fin-neat/in-fin-neat-core/pull/50#discussion_r1864882620

For eg:
```
iban_set = set(user.ibanList)
iban_set.add(newIban)
iban_list = list(iban_set)
```

**Comment by diegotsutsumi** [comment]
Closing in favor of https://github.com/in-fin-neat/in-fin-neat-core/issues/56
